### ISSUE TITLE
其实很久以前中科院有翻译过一版 RISC-V 的 Spec（

### ISSUE THREAD

**Issue by wfly1998** [imlyzh/riscv-ysyx-manual-cn#1]
时间有点久了，仅供参考

另外，源文件已经删了，现在只能从 `webarchive` 下载到

https://web.archive.org/web/20190819065650if_/http://crva.io:80/documents/RISC-V-Reader-Chinese-v2p1.pdf

**Comment by imlyzh** [comment]
> 时间有点久了，仅供参考
> 
> 
> 
> 另外，源文件已经删了，现在只能从 `webarchive` 下载到
> 
> 
> 
> https://web.archive.org/web/20190819065650if_/http://crva.io:80/documents/RISC-V-Reader-Chinese-v2p1.pdf

啊，我知道这个。我写的的标题可能有点不明确，其实这里指的是特权级和中断这块。
这本书里似乎没有翻译这部分
